# Generated by Django 3.1.7 on 2021-04-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name_plural': 'User Addresses'},
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='related_order',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='booking_manager.ProductOrder'),
        ),
    ]
