# Generated by Django 3.1.7 on 2021-05-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0002_auto_20210516_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='reserve',
        ),
    ]
