# Generated by Django 3.1.7 on 2021-04-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0002_auto_20210412_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='products_ordered',
        ),
    ]
