# Generated by Django 3.1.7 on 2021-05-19 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking_manager', '0003_remove_table_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expected_delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='distance_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
