# Generated by Django 3.1.7 on 2021-05-19 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0004_auto_20210519_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='distance_seconds',
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 20, 59, 40, 930531, tzinfo=utc)),
        ),
    ]
