# Generated by Django 3.1.7 on 2021-05-05 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0005_auto_20210412_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER', 'Order done'), ('PREPARING', 'Preparing'), ('DELIVERING', 'Delivering'), ('COMPLETED', 'Completed')], default='ORDER', max_length=15),
        ),
    ]
