# Generated by Django 3.1.7 on 2021-05-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0006_auto_20210505_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('DELIVERING', 'Delivering'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15),
        ),
    ]
