version: "3.3"
services:
  db:
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_DB=pyoli
      - POSTGRES_USER=pyoli
      - POSTGRES_PASSWORD=pyoli
  app:
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
